From elpi.apps Require Import coercion.
From HB Require Import structures.
From mathcomp Require Import ssreflect ssrfun ssrbool ssrint ssrnat all_order.
From mathcomp Require Import eqtype seq fintype all_algebra div.
From mathcomp Require Import ring lra zify choice.
Require Import Setoid Morphisms.

Import GRing.Theory.

From GWP Require Import Utils Equivalence
  EquivalenceAlgebra Presentation F2 GeneratedSubgroup
  NielsenSchreier Sizelexi Preorder.

Open Scope int_scope.
Open Scope ring_scope.

Import PresentationNotations.
(** In this section we develop the Nielsen-Schreier-Stallings
    theory of subgroups of the free group, as it applies
    to the subgroup generated by a_p = b^p a b^{-p} and b^q. *)
Section NielsenSchreierStallings.

Let Sigma := ordinal 2.
Let F2P := FGP Sigma.
Let F2 := FreeGroup Sigma.
Notation a := (Base 0).
Notation b := (Base 1).
Notation "a^-1" := (Inverse 0).
Notation "b^-1" := (Inverse 1).

(* NOTE(reiniscirpons): a_p = b^p a b^{-p} *)
Definition a_encoding (p: int): F2 :=
  (power (`[b]_F2P) p) @ (`[a]_F2P) @ inv (power (`[b]_F2P) p).

(* NOTE(reiniscirpons): b^q is the other generator *)
Definition b_encoding (q: int): F2 := power (`[b]_F2P) q.

Variable p q: int.

Let gens := [:: a_encoding p; b_encoding q].
(* TODO: Why is Gamma not equal to Sigma? Shouldn't they be because
         length gens computationally reduces to 2? *)
Let Gamma := ordinal (size gens).
Let IndexFG := FreeGroup Gamma.
Let K := generatedSubgroup gens.

(* NOTE(reiniscirpons): This is the map a -> a_p and b -> b^q,
   we will show it is an isomorphism onto <a_p, b^q> later on. *)
(* TODO(reiniscirpons): Why does this not work without explicitly
        specifying the group and subgroup? *)
Definition apbq_projection: morphism IndexFG F2 := 
  (@subgroup_inj F2 K) \o (subgroup_projection gens).

(* TODO(reiniscirpons): We need to probably get rid of prod or change
   its definition to be recursive on the input list instead of 
   having the iterated definition that is too hard to reason about
   (when we eliminate it causes a lot of headache) *)
Lemma apbq_projection_cons: forall h t,
  apbq_projection (h::t) =
    (match h with
    | Base o => if (o == 0)%B then a_encoding p else b_encoding q
    | Inverse o => inv (if (o == 0)%B then a_encoding p else b_encoding q)
    end) ++ apbq_projection t.
Proof. by move => [|] [] [|[|//]]. Qed.

Lemma fra_encode: forall n, freely_reduced (a_encoding n).
Proof.
  move => n; case: (n =P 0) => [Heq0 | Hdiff Hn]; last first.
  rewrite /a_encoding /inv /= -power_inv_word -[power _ (- n)]cats0.
  set x := [::a] \mod (FGP Sigma).
  rewrite -[x]FreeGroup_power1 /x
  [power]lock -!cat_law -catA !cat_law -lock.
  apply (freely_reduced_power _
          ([::b; a; b] \mod (FGP Sigma))
          [:: n; 1; -n]) => [//||//|//].
  apply /allP => m.
  rewrite !in_cons => /orP [|/orP [|/orP [|//]]]; by lia.

  (* 0 case *)

  by rewrite /a_encoding Heq0 /= power0 -!cat_law cats0 cat0s freely_reduced_correct.
Qed.

Variable Hqn0: (q != 0)%N.
Variable Hpq: (`|p|*2 <= `|q|)%N.

Lemma apbq_minimal: @minimality_condition _ gens.
Proof.
  have Hred: (forall w, freely_reduced w -> FreeGroup_norm w = w);
    first by move => T w /freely_reduced_correct.
  move => [|[|[|[|//]]]] [|[|[|[|//]]]] _ _ // _ /=;
  rewrite /a_encoding /b_encoding /= =>
    /Order.PreorderTheory.ltW /CmpOrder.cmp_sz_le /=;
  rewrite /CmpOrder.sz /=;
  case Hp: p Hpq => [//|p'] Hpq';
  case Hq: q Hpq' => [//|q'] Hpq'.
  (* Make tactic to take care of this *)
  rewrite -Hp !associativity -5!associativity 
          [(inv _) @ _]associativity inverse_right
          neutral_left -(FreeGroup_power1 _ ([::a]: F2))
          -power_inv [power]lock !associativity -lock
          -[(_ @ _) @ power _ 1]associativity
          -power_add -[power _ (- _)]cats0
          [power]lock
          -!associativity -lock.
  rewrite !Hred.
  - rewrite !size_cat !(@size_power F2P) /=; lia.
  - case: (p =P 0) => [-> | Hn0].
    + rewrite power0 -cat_law cats0 cat0s -cat_law cats0; apply: freely_reduced_power1.
    apply (freely_reduced_power _
          ([::b; a; b] \mod (FGP Sigma))
          [:: (p: int); 1; -(p: int)]) => [//||//|//].
    apply/allP => m.
    rewrite !in_cons => /orP [|/orP [|/orP [|//]]]; by lia.
  - case: (p =P 0) => [-> | Hn0].
    + rewrite power0 -cat_law cats0 cat0s -cat_law cats0; apply: freely_reduced_power1.

    apply (freely_reduced_power _
          ([::b; a; b] \mod (FGP Sigma))
          [:: (p: int); 2; -(p: int)]) => [//||//|//].
    apply/allP => m.
    rewrite !in_cons => /orP [|/orP [|/orP [|//]]]; by lia.
  (* Only 21 cases to go! *)
Admitted.


Lemma frgens: forall x, x \in gens -> freely_reduced x.
Proof.
  move => x.
  rewrite /gens in_cons => /orP [/eqP -> |].
  case: (p =P 0) => [-> |/eqP].
  + rewrite /a_encoding power0 -!cat_law cats0 cat0s.
    by rewrite freely_reduced_correct.
  
  + move => Hlt0.
    by apply: fra_encode.
  - rewrite in_cons => /orP [/eqP -> |//].
    apply: freely_reduced_power1.
Qed.
  
Lemma non_trivial: forall x, x \in gens -> FreeGroup_norm x != e.
Proof.
  move => x ingens.
  move: (frgens x ingens).
  rewrite /gens in_cons in ingens; move: ingens => /orP [/eqP -> |].
  rewrite freely_reduced_correct => <-; rewrite /a_encoding.
  apply/eqP => Habs.
  by move/(f_equal size) in Habs; rewrite -!cat_law !size_cat /= in Habs; lia.
  rewrite in_cons freely_reduced_correct => /orP [/eqP -> |//] <-; rewrite /b_encoding.
  apply/eqP => Habs.
  move/(f_equal size) in Habs; rewrite /= (@size_power F2P) in Habs.
  by lia.
Qed.


Definition apbq_isomorphism: isomorphism F2 K.
Proof.
  move: (@sub_freegroup_iso Sigma gens).
  move: (@NielsenR_fixpoint Sigma gens apbq_minimal frgens non_trivial) => -> /=.
  by done.
Qed.

Definition isomorphismP (x: K) :=
  (fun y => (FreeGroup_norm((apbq_isomorphism y).(sb_point)) == FreeGroup_norm (x.(sb_point)))%B).

Lemma exist_isomorphismP (x: K):
  exists x0 : F2, (isomorphismP x x0).
Proof.
  move: (@surjectivity_property _ _ apbq_isomorphism x); move: x.

  rewrite /K /generatedSubgroup /isomorphismP => x H.

  case: H => x0 Heq.
  exists (x0).
  rewrite /eq /= /subgroupby_eq /subgroupby_inj in Heq.
  by rewrite Heq.
Qed.
  

Definition apbq_isomorphism_inv': K -> F2.
Proof.
  move => x.
  by apply: (@xchoose F2 (isomorphismP x) (exist_isomorphismP x)).
Defined.

Lemma apbq_inverse_right: forall x, apbq_isomorphism (apbq_isomorphism_inv' x) == x.
Proof.
  rewrite /apbq_isomorphism_inv' /= => x.
  move: (xchooseP (exist_isomorphismP x)).
  rewrite /isomorphismP /subgroupby_eq /subgroupby_inj -/FreeGroup_dec_eq.
  by apply: FreeGroup_dec_eq_to_eqprop.
Qed.

Lemma apbq_preserve_equiv: forall x y, x == y -> apbq_isomorphism_inv' x == apbq_isomorphism_inv' y.
Proof.
  move => x y eqxy.
  rewrite /apbq_isomorphism_inv'.
  rewrite (eq_xchoose (exist_isomorphismP x) (exist_isomorphismP y)) //.
  rewrite /isomorphismP => z.
  by rewrite /eq /= /subgroupby_eq /subgroupby_inj in eqxy; move/eqprop_to_FreeGroup_dec_eq in eqxy; rewrite /FreeGroup_dec_eq in eqxy; move/eqP in eqxy; rewrite {}eqxy.
Qed.

HB.instance Definition _ :=
    isIsomorphismRightInverse.Build _ _ apbq_isomorphism apbq_isomorphism_inv'
      apbq_preserve_equiv
      apbq_inverse_right.

Definition apbq_isomorphism_inv: isomorphism K F2 := apbq_isomorphism_inv'.

End NielsenSchreierStallings.

Section apbqIsomorphismHousekeeping.

Variable p q: int.
Let gens := [:: a_encoding p; b_encoding q].
Variable Hq: (q != 0)%Z.

Definition pq_isomorphism_inv:
  isomorphism
    (generatedSubgroup gens)
    (generatedSubgroup [:: a_encoding p; b_encoding (-q)]).
Proof.
  set gens_inv := map inv gens.
  move: (generatedSubgroup_inv_morphism gens:
    isomorphism (generatedSubgroup gens) (generatedSubgroup gens_inv)) => f1.
  set gens_rcons := rcons gens_inv (a_encoding p).
  have: in_generated_subgroup gens_inv (a_encoding p) => [|H];
    first by exists [:: Inverse 0] => /=; rewrite inv_involutive neutral_right.
  move: (generatedSubgroup_rcons_morphism gens_inv (a_encoding p) H:
    isomorphism (generatedSubgroup gens_inv) (generatedSubgroup gens_rcons)) => f2.
  set gens' := [:: a_encoding p; b_encoding (-q)].
  set gens_rcons' := rcons gens' (inv (a_encoding p)).
  set perm :(ordinal (size gens_rcons)) -> (ordinal (size gens_rcons')) :=
    fun x =>
      match x with
      | @Ordinal _ 0 _ => 2
      | @Ordinal _ 1 _ => 1
      | @Ordinal _ 2 _ => 0
      | _ => x
      end.
  have: injective perm => [|Hperm_inj];
    first by move => [] [|[|[|//]]] Hx [] [|[|[|//]]] Hy /= /eqP // _;
    rewrite (bool_irrelevance Hx Hy).
  have: bijective perm => [|Hperm];
    first by apply inj_card_bij => [//|] /=; apply leqnn.
  have: forall n, nth_gen gens_rcons n == nth_gen gens_rcons' (perm n) => [|Hequiv];
    first by move => [] [//|[|[//|//]]] /= _; rewrite -power_inv.
  move: (generatedSubgroup_perm_morphism gens_rcons gens_rcons' perm Hequiv Hperm:
    isomorphism (generatedSubgroup gens_rcons) (generatedSubgroup gens_rcons')) => f3.
  have: in_generated_subgroup gens' (inv (a_encoding p)) => [|H'];
    first by exists [:: Inverse 0] => /=; rewrite neutral_right.
  move: (generatedSubgroup_rcons_morphism' gens' (inv (a_encoding p)) H':
    isomorphism (generatedSubgroup gens_rcons') (generatedSubgroup gens')) => f4.
  by exact: (f4 \o f3 \o f2 \o f1).
Defined.

Definition pq_isomorphism_mod:
  isomorphism
    (generatedSubgroup gens)
    (generatedSubgroup [:: a_encoding (p %% q)%Z; b_encoding q]).
Proof.
  set gens' := [:: a_encoding (p %% q)%Z; b_encoding q].
  set gens_rcons := rcons gens (a_encoding (p %% q)%Z).
  have: in_generated_subgroup gens (a_encoding (p %% q)%Z) => [|H].
  - exists ((power (`[Base 1]_(FGP _)) (- (p %/ q)%Z)) @ [:: Base 0] @
           (power (`[Base 1]_(FGP _)) (p %/ q)%Z)).
    rewrite !morphism_preserve_law !morphism_preserve_power /=
            !neutral_right /b_encoding -!power_mul /a_encoding
            !associativity -power_add -!associativity
            -!power_inv -power_add.
    have: (q * - (p %/ q)%Z + p = p %%q)%Z => [|->]; first by lia.
    by have: (-p + q * (p %/ q)%Z = - (p %%q)%Z)%Z => [|->]; first by lia.
  - move: (generatedSubgroup_rcons_morphism gens (a_encoding (p %% q)%Z) H:
      isomorphism (generatedSubgroup gens) (generatedSubgroup gens_rcons)) => f1.
    set gens_rcons' := rcons gens' (a_encoding p).
    set perm :(ordinal (size gens_rcons)) -> (ordinal (size gens_rcons')) :=
      fun x =>
        match x with
        | @Ordinal _ 0 _ => 2
        | @Ordinal _ 1 _ => 1
        | @Ordinal _ 2 _ => 0
        | _ => x
        end.
    have: injective perm => [|Hperm_inj];
      first by move => [] [|[|[|//]]] Hx [] [|[|[|//]]] Hy /= /eqP // _;
      rewrite (bool_irrelevance Hx Hy).
    have: bijective perm => [|Hperm];
      first by apply inj_card_bij => [//|] /=; apply leqnn.
    have: forall n, nth_gen gens_rcons n == nth_gen gens_rcons' (perm n) => [|Hequiv];
      first by move => [] [//|[|[//|//]]] /= _.
    move: (generatedSubgroup_perm_morphism gens_rcons gens_rcons' perm Hequiv Hperm:
      isomorphism (generatedSubgroup gens_rcons) (generatedSubgroup gens_rcons')) => f2.
    have: in_generated_subgroup gens' (a_encoding p) => [|H'].
  -- exists ((power (`[Base 1]_(FGP _)) (p %/ q)%Z) @ [:: Base 0] @
        (power (`[Base 1]_(FGP _)) (- (p %/ q)%Z))).
     rewrite !morphism_preserve_law !morphism_preserve_power /=
              !neutral_right /b_encoding -!power_mul /a_encoding
              !associativity -power_add -!associativity
              -!power_inv -power_add.
     have: (q * (p %/ q)%Z + (p%%q)%Z = p)%Z => [|->]; first by lia.
     by have: (- (p %% q)%Z + q * - (p %/ q)%Z = - p)%Z => [|->]; first by lia.
  -- move: (generatedSubgroup_rcons_morphism' gens' (a_encoding p) H':
       isomorphism (generatedSubgroup gens_rcons') (generatedSubgroup gens')) => f3.
     by exact: (f3 \o f2 \o f1).
Defined.

Definition pq_isomorphism_mod':
  isomorphism
    (generatedSubgroup [:: a_encoding (p %% q)%Z; b_encoding q])
    (generatedSubgroup gens).
Proof.
  set gens' := [:: a_encoding (p %% q)%Z; b_encoding q].
  set gens_rcons' := rcons gens' (a_encoding p).
  have: in_generated_subgroup gens' (a_encoding p) => [|H'].
  - exists ((power (`[Base 1]_(FGP _)) (p %/ q)%Z) @ [:: Base 0] @
        (power (`[Base 1]_(FGP _)) (- (p %/ q)%Z))).
     rewrite !morphism_preserve_law !morphism_preserve_power /=
              !neutral_right /b_encoding -!power_mul /a_encoding
              !associativity -power_add -!associativity
              -!power_inv -power_add.
     have: (q * (p %/ q)%Z + (p%%q)%Z = p)%Z => [|->]; first by lia.
     by have: (- (p %% q)%Z + q * - (p %/ q)%Z = - p)%Z => [|->]; first by lia.
  - move: (generatedSubgroup_rcons_morphism gens' (a_encoding p) H':
       isomorphism (generatedSubgroup gens') (generatedSubgroup gens_rcons')) => f1.
    set gens_rcons := rcons gens (a_encoding (p %% q)%Z).

    set perm :(ordinal (size gens_rcons')) -> (ordinal (size gens_rcons)) :=
      fun x =>
        match x with
        | @Ordinal _ 0 _ => 2
        | @Ordinal _ 1 _ => 1
        | @Ordinal _ 2 _ => 0
        | _ => x
        end.
    have: injective perm => [|Hperm_inj];
      first by move => [] [|[|[|//]]] Hx [] [|[|[|//]]] Hy /= /eqP // _;
      rewrite (bool_irrelevance Hx Hy).
    have: bijective perm => [|Hperm];
      first by apply inj_card_bij => [//|] /=; apply leqnn.
    have: forall n, nth_gen gens_rcons' n == nth_gen gens_rcons (perm n) => [|Hequiv];
      first by move => [] [//|[|[//|//]]] /= _.
    move: (generatedSubgroup_perm_morphism gens_rcons' gens_rcons perm Hequiv Hperm:
      isomorphism (generatedSubgroup gens_rcons') (generatedSubgroup gens_rcons)) => f2.

    have: in_generated_subgroup gens (a_encoding (p %% q)%Z) => [|H].
  -- exists ((power (`[Base 1]_(FGP _)) (- (p %/ q)%Z)) @ [:: Base 0] @
           (power (`[Base 1]_(FGP _)) (p %/ q)%Z)).
     rewrite !morphism_preserve_law !morphism_preserve_power /=
             !neutral_right /b_encoding -!power_mul /a_encoding
             !associativity -power_add -!associativity
             -!power_inv -power_add.
     have: (q * - (p %/ q)%Z + p = p %%q)%Z => [|->]; first by lia.
     by have: (-p + q * (p %/ q)%Z = - (p %%q)%Z)%Z => [|->]; first by lia.
  -- move: (generatedSubgroup_rcons_morphism' gens (a_encoding (p %% q)%Z) H:
       isomorphism (generatedSubgroup gens_rcons) (generatedSubgroup gens)) => f3.
     by exact: (f3 \o f2 \o f1).
Defined.

End apbqIsomorphismHousekeeping.

Definition pq_isomorphism_nat (p q: int) (H: (q != 0)%Z):
  isomorphism
    (generatedSubgroup [:: a_encoding p; b_encoding q])
    (generatedSubgroup [:: a_encoding `|(p %% q)%Z|%N; b_encoding `|q|%N]).
Proof.
  move: (pq_isomorphism_mod p q H).
  have: ((p %% q)%Z = `|(p%% q)%Z|%N) => [|-> f1]; first by lia.
  case Hq0: (q >= 0)%Z.
  - have: (q = `|q|%N) => [|<-]; first by lia.
    by exact: f1.
  - move: (pq_isomorphism_inv (`|(p%%q)%Z|%N) q).
    have: ((-q)%Z = `|q|%N) => [|-> f2]; first by lia.
    by exact: (f2 \o f1).
Qed.

Definition pq_isomorphism_nat' (p q: int) (H: (q != 0)%Z):
  isomorphism
    (generatedSubgroup [:: a_encoding `|(p %% q)%Z|%N; b_encoding `|q|%N])
    (generatedSubgroup [:: a_encoding p; b_encoding q]).
Proof.
  move: (pq_isomorphism_mod' p q H).
  have: ((p %% q)%Z = `|(p%% q)%Z|%N) => [|-> f2]; first by lia.
  case Hq0: (q >= 0)%Z.
  - have: (q = `|q|%N) => [|<-]; first by lia.
    by exact: f2.
  - move: (pq_isomorphism_inv (`|(p %% q)%Z|%N) (-q)%Z).
    have: (- (-q)%Z = q) => [|->]; first by lia.
    have: ((-q)%Z = `|q|%N) => [|-> f1]; first by lia.
    by exact: (f2 \o f1).
Qed.

Lemma nat''_eq_size (p q: int) (H: (q != 0)%Z) (Hp: (p != 0)%Z) (Hlt: `|p| < `|q|%N):
  `|(p %% q)%Z| - `|q| = -(-p %% q)%Z.
Proof.
  case: (boolP (0 < p)%Z) => [Hpos | Hneg].
  - rewrite -modz_abs.
    rewrite modz_small.
    rewrite -modz_abs.
    have -> : (-p %% `|q|)%Z = ((`|q| - p) %% `|q|)%Z.
      by rewrite modzDl.
    rewrite modz_small.
    have -> : `|p| = p.
      by apply: gtz0_abs.
    by lia.
    - by lia.
    - by lia.

  - move: Hp; case: (p =P 0) => [-> // | Hn0 _].
    + rewrite -modz_abs.
      have -> : `|(p %% `|q|)%Z| = `|((`|q| + p) %% `|q|)%Z|.
        by rewrite modzDl.
      rewrite modz_small.
      rewrite -modz_abs modz_small.
      by lia.
      + by lia.
      + by lia.
Qed.

  
Definition pq_isomorphism_nat'' (p q: int) (H: (q != 0)%Z):
  isomorphism
    (generatedSubgroup [:: a_encoding (p - q); b_encoding q])
    (generatedSubgroup [:: a_encoding p; b_encoding q]).
Proof.

  pose s0 := [:: a_encoding p; b_encoding q].

  pose s1 := t2 s0 0 1.
  have H1: (0 < size s0)%N by done.
  have H1': (1 < size s0)%N by done.
  have Hdiff1: (0 <> 1)%N by done.
  move: (@id_gen_morphism _ s0 s1 (t2_equal_subgroup s0 0 1 H1 H1' Hdiff1): isomorphism _ _) => f1.
  
  pose s2 := t1 s1 0.
  have H2: (0 < size s1)%N by done.
  move: (@id_gen_morphism _ s1 s2 (t1_equal_subgroup s1 0 H1): isomorphism _ _) => f2.

  pose s3 := t2 s2 0 1.
  have H3: (0 < size s2)%N by done.
  have H3': (1 < size s2)%N by done.
  have Hdiff3: (0 <> 1)%N by done.
  move: (@id_gen_morphism _ s2 s3 (t2_equal_subgroup s2 0 1 H3 H3' Hdiff3): isomorphism _ _) => f3.

  pose s4 := t1 s3 0.
  have H4: (0 < size s3)%N by done.
  move: (@id_gen_morphism _ s3 s4 (t1_equal_subgroup s3 0 H4): isomorphism _ _) => f4.

  have eqs4 : s4 = [:: a_encoding (p - q); b_encoding q].
    rewrite /s4 /s3 /s2 /s1 /s0 /t1 /t2 /= -!FreeGroup_norm_inv inverse_law -!FreeGroup_norm_inv.
    have eqbq : b_encoding q = FreeGroup_norm (b_encoding q).
      rewrite -freely_reduced_correct.
      apply: freely_reduced_power1.
    rewrite eqbq.
    rewrite !FreeGroup_norm_involutive -FreeGroup_norm_inv -FreeGroup_norm_law.
    rewrite -{1}eqbq inv_eq_invol.

    move: (fra_encode (p - q)); rewrite freely_reduced_correct => ->.
    apply: (@eq_from_nth _ e) => //.
    move => i /= ibnd.
    case: i ibnd => [|[//|//]] ibnd /=.
    - apply: FreeGroup_norm_unique; rewrite /a_encoding !associativity power_add powerC.
      by rewrite inverse_law power_inv inv_eq_invol !associativity.

  rewrite -eqs4.
  exact: (f1 \o f2 \o f3 \o f4).
Qed.


Definition pq_isomorphism_nat''_inv (p q: int) (H: (q != 0)%Z):
  isomorphism
    (generatedSubgroup [:: a_encoding p; b_encoding q])
    (generatedSubgroup [:: a_encoding (p - q); b_encoding q]).
Proof.

  pose s0 := [:: a_encoding p; b_encoding q].

  pose s1 := t2 s0 0 1.
  have H1: (0 < size s0)%N by done.
  have H1': (1 < size s0)%N by done.
  have Hdiff1: (0 <> 1)%N by done.
  move: (@id_gen_morphism_inv _ s0 s1 (t2_equal_subgroup s0 0 1 H1 H1' Hdiff1): isomorphism _ _) => f1.
  
  pose s2 := t1 s1 0.
  have H2: (0 < size s1)%N by done.
  move: (@id_gen_morphism_inv _ s1 s2 (t1_equal_subgroup s1 0 H1): isomorphism _ _) => f2.

  pose s3 := t2 s2 0 1.
  have H3: (0 < size s2)%N by done.
  have H3': (1 < size s2)%N by done.
  have Hdiff3: (0 <> 1)%N by done.
  move: (@id_gen_morphism_inv _ s2 s3 (t2_equal_subgroup s2 0 1 H3 H3' Hdiff3): isomorphism _ _) => f3.

  pose s4 := t1 s3 0.
  have H4: (0 < size s3)%N by done.
  move: (@id_gen_morphism_inv _ s3 s4 (t1_equal_subgroup s3 0 H4): isomorphism _ _) => f4.

  have eqs4 : s4 = [:: a_encoding (p - q); b_encoding q].
    rewrite /s4 /s3 /s2 /s1 /s0 /t1 /t2 /= -!FreeGroup_norm_inv inverse_law -!FreeGroup_norm_inv.
    have eqbq : b_encoding q = FreeGroup_norm (b_encoding q).
      rewrite -freely_reduced_correct.
      apply: freely_reduced_power1.
    rewrite eqbq.
    rewrite !FreeGroup_norm_involutive -FreeGroup_norm_inv -FreeGroup_norm_law.
    rewrite -{1}eqbq inv_eq_invol.

    move: (fra_encode (p - q)); rewrite freely_reduced_correct => ->.
    apply: (@eq_from_nth _ e) => //.
    move => i /= ibnd.
    case: i ibnd => [|[//|//]] ibnd /=.
    - apply: FreeGroup_norm_unique; rewrite /a_encoding !associativity power_add powerC.
      by rewrite inverse_law power_inv inv_eq_invol !associativity.

  rewrite -eqs4.
  exact: (f4 \o f3 \o f2 \o f1).
Qed.


(* TODO(reiniscirpons): uncomment and fix once we have a lemma
   for the isomorphism. *)

Lemma p2q_lt (p q: int) (H: (q != 0)%Z) (Hp: (p != 0)%Z) (H2lt: `|q| < `|(p %% q)%Z|*2):
  ( `| (`|p %% q|%Z - `|q|%Z )%R| * 2 <= `| `|q|%R | )%N.
Proof.
  by lia.
Qed.

Definition pqpq_isomorphism
  (p1 q1: int) (H1: (q1 != 0)%Z)
  (p2 q2: int) (H2: (q2 != 0)%Z):
  isomorphism (generatedSubgroup [:: a_encoding p1; b_encoding q1])
    (generatedSubgroup [:: a_encoding p2; b_encoding q2]).
Proof.
  move: (pq_isomorphism_nat p1 q1 H1) => f1.

  have H1' : `|q1| != 0 by lia.
  have H2' : `|q2| != 0 by lia.
  
  case: (boolP ((`|(p1 %% q1)%Z| * 2 <= `|q1|)%N)) => [Hs1|Hc1].
  case: (boolP ((`|(p2 %% q2)%Z| * 2 <= `|q2|)%N)) => [Hs2|Hc2].
  + move: (apbq_isomorphism_inv (`|(p1 %% q1)%Z|%N) (`|q1|%N) H1' Hs1) => f2.
    move: (apbq_isomorphism (`|(p2 %% q2)%Z|%N) (`|q2|%N) H2' Hs2) => f3.
    move: (pq_isomorphism_nat' p2 q2 H2) => f4.
  
    exact: (f4 \o f3 \o f2 \o f1).
  + move: (apbq_isomorphism_inv (`|(p1 %% q1)%Z|%N) (`|q1|%N) H1' Hs1) => f2.
    move: (pq_isomorphism_nat'' (`|(p2 %% q2)%Z|%N) (`|q2|%N) H2') => f4.
    move: (pq_isomorphism_nat' p2 q2 H2) => f5.

    have Hle2'' : (`|(`|(p2 %% q2)%Z| - `|q2|)%R| * 2 <= `| `|q2|%R |)%N.
      apply : p2q_lt.
      + exact: H2.
      + apply/eqP => eq0.
        by rewrite eq0 mod0z /= in Hc2.
      + by lia.
        
    move: (apbq_isomorphism (`|(p2 %% q2)%Z| - `|q2|) (`|q2|%N) H2' Hle2'') => f3.
    exact: (f5 \o f4 \o f3 \o f2 \o f1).
  case: (boolP ((`|(p2 %% q2)%Z| * 2 <= `|q2|)%N)) => [Hs2|Hc2].
  + move: (pq_isomorphism_nat''_inv (`|(p1 %% q1)%Z|%N) (`|q1|%N) H1') => f2.

    have Hle1'' : (`|(`|(p1 %% q1)%Z| - `|q1|)%R| * 2 <= `| `|q1| |)%N.
      apply : p2q_lt.
      exact: H1.
      + apply/eqP => eq0.
        by rewrite eq0 mod0z /= in Hc1.
      + by lia.

    move: (apbq_isomorphism_inv ((`|(p1 %% q1)%Z| - `|q1|%Z)) (`|q1|%N) H1' Hle1'') => f3.
    move: (apbq_isomorphism (`|(p2 %% q2)%Z|%N) (`|q2|%N) H2' Hs2) => f4.
    move: (pq_isomorphism_nat' p2 q2 H2) => f5.

    exact: (f5 \o f4 \o f3 \o f2 \o f1).

  + move: (pq_isomorphism_nat''_inv (`|(p1 %% q1)%Z|%N) (`|q1|%N) H1') => f2.

    have Hle1'' : (`|(`|(p1 %% q1)%Z| - `|q1|)%R| * 2 <= `| `|q1| |)%N.
      apply : p2q_lt.
      exact: H1.
      + apply/eqP => eq0.
        by rewrite eq0 mod0z /= in Hc1.
      + by lia.

    move: (apbq_isomorphism_inv ((`|(p1 %% q1)%Z| - `|q1|%Z)) (`|q1|%N) H1' Hle1'') => f3.
    move: (pq_isomorphism_nat'' (`|(p2 %% q2)%Z|%N) (`|q2|%N) H2') => f5.
    move: (pq_isomorphism_nat' p2 q2 H2) => f6.

    have Hle2'' : (`|(`|(p2 %% q2)%Z| - `|q2|)%R| * 2 <= `| `|q2|%R |)%N.
      apply : p2q_lt.
      + exact: H2.
      + apply/eqP => eq0.
        by rewrite eq0 mod0z /= in Hc2.
      + by lia.
        
    move: (apbq_isomorphism (`|(p2 %% q2)%Z| - `|q2|) (`|q2|%N) H2' Hle2'') => f4.
    exact: (f6 \o f5 \o f4 \o f3 \o f2 \o f1).
Defined.
