From elpi.apps Require Import coercion.
From HB Require Import structures.
From mathcomp Require Import ssreflect ssrfun ssrbool ssrint ssrnat all_order.
From mathcomp Require Import eqtype seq fintype all_algebra div.
From mathcomp Require Import ring lra zify choice.
Require Import Setoid Morphisms.

From GWP Require Import Utils Equivalence
  EquivalenceAlgebra Presentation F2 GeneratedSubgroup
  NielsenSchreier Sizelexi Preorder.

Open Scope int_scope.
Open Scope ring_scope.

Import PresentationNotations.
(** In this section we develop the Nielsen-Schreier-Stallings
    theory of subgroups of the free group, as it applies
    to the subgroup generated by a_p = b^p a b^{-p} and b^q. *)
Section NielsenSchreierStallings.

Let Sigma := ordinal 2.
Let F2P := FGP Sigma.
Let F2 := FreeGroup Sigma.
Notation a := (Base 0).
Notation b := (Base 1).
Notation "a^-1" := (Inverse 0).
Notation "b^-1" := (Inverse 1).

(* NOTE(reiniscirpons): a_p = b^p a b^{-p} *)
Definition a_encoding (p: int): F2 :=
  (power (`[b]_F2P) p) @ (`[a]_F2P) @ inv (power (`[b]_F2P) p).

(* NOTE(reiniscirpons): b^q is the other generator *)
Definition b_encoding (q: int): F2 := power (`[b]_F2P) q.

Variable p q: nat.

Let gens := [:: a_encoding p; b_encoding q].
(* TODO: Why is Gamma not equal to Sigma? Shouldn't they be because
         length gens computationally reduces to 2? *)
Let Gamma := ordinal (size gens).
Let IndexFG := FreeGroup Gamma.
Let K := generatedSubgroup gens.

(* NOTE(reiniscirpons): This is the map a -> a_p and b -> b^q,
   we will show it is an isomorphism onto <a_p, b^q> later on. *)
(* TODO(reiniscirpons): Why does this not work without explicitly
        specifying the group and subgroup? *)
Definition apbq_projection: morphism IndexFG F2 := 
  (@subgroup_inj F2 K) \o (subgroup_projection gens).

(* TODO(reiniscirpons): We need to probably get rid of prod or change
   its definition to be recursive on the input list instead of 
   having the iterated definition that is too hard to reason about
   (when we eliminate it causes a lot of headache) *)
Lemma apbq_projection_cons: forall h t,
  apbq_projection (h::t) =
    (match h with
    | Base o => if (o == 0)%B then a_encoding p else b_encoding q
    | Inverse o => inv (if (o == 0)%B then a_encoding p else b_encoding q)
    end) ++ apbq_projection t.
Proof. by move => [|] [] [|[|//]]. Qed.

Variable Hpq: (p*2 < q)%N.

Goal forall n, n!=0 -> freely_reduced (a_encoding n).
Proof.
  move => n Hn;
  rewrite /a_encoding /inv /= -power_inv_word -[power _ (- n)]cats0.
  set x := [::a] \mod (FGP Sigma).
  rewrite -[x]FreeGroup_power1 /x
  [power]lock -!cat_law -catA !cat_law -lock.
  apply (freely_reduced_power _
          ([::b; a; b] \mod (FGP Sigma))
          [:: n; 1; -n]) => [//||//|//].
  apply /allP => m.
  rewrite !in_cons => /orP [|/orP [|/orP [|//]]]; by lia.
Qed.

(* TODO(reiniscirpons): remove once lemma is proved. *)
Lemma size_power: forall (w: FreeGroup Sigma) (n: int),
  size (power w n) = `|n|%N.
Proof.
Admitted.

Lemma apbq_minimal: @minimality_condition _ gens.
Proof.
  have Hred: (forall w, freely_reduced w -> FreeGroup_norm w = w);
    first by move => T w /freely_reduced_correct.
  move => [|[|[|[|//]]]] [|[|[|[|//]]]] _ _ // _ /=;
  rewrite /a_encoding /b_encoding /= =>
    /Order.PreorderTheory.ltW /CmpOrder.cmp_sz_le /=;
  rewrite /CmpOrder.sz /=;
  case Hp: p Hpq => [//|p'] Hpq';
  case Hq: q Hpq' => [//|q'] Hpq'.
  (* Make tactic to take care of this *)
  rewrite -Hp !associativity -5!associativity 
          [(inv _) @ _]associativity inverse_right
          neutral_left -(FreeGroup_power1 _ ([::a]: F2))
          -power_inv [power]lock !associativity -lock
          -[(_ @ _) @ power _ 1]associativity
          -power_add -[power _ (- _)]cats0
          [power]lock
          -!associativity -lock.
  rewrite !Hred.
  - by rewrite !size_cat !size_power /=; lia.
  - apply (freely_reduced_power _
          ([::b; a; b] \mod (FGP Sigma))
          [:: (p: int); 1; -(p: int)]) => [//||//|//].
    apply/allP => m.
    rewrite !in_cons => /orP [|/orP [|/orP [|//]]]; by lia.
  - apply (freely_reduced_power _
          ([::b; a; b] \mod (FGP Sigma))
          [:: (p: int); 2; -(p: int)]) => [//||//|//].
    apply/allP => m.
    rewrite !in_cons => /orP [|/orP [|/orP [|//]]]; by lia.
  (* Only 21 cases to go! *)
Admitted.

Definition apbq_isomorphism: isomorphism F2 K.
Admitted.

(*Definition apbq_isomorphism_inv': K -> F2.*)
(*Proof.*)
(*  move => x.*)
(*  move: (@surjectivity_property _ _ apbq_isomorphism x) => H.*)
(*  move: (xchoose H).*)

(*Definition apbq_isomorphism_inv: isomorphism K F2.*)
(*Proof.*)
  

End NielsenSchreierStallings.

Section apbqIsomorphismHousekeeping.

Variable p q: int.
Let gens := [:: a_encoding p; b_encoding q].
Variable Hq: (q != 0)%Z.

Definition pq_isomorphism_inv:
  isomorphism
    (generatedSubgroup gens)
    (generatedSubgroup [:: a_encoding p; b_encoding (-q)]).
Proof.
  set gens_inv := map inv gens.
  move: (generatedSubgroup_inv_morphism gens:
    isomorphism (generatedSubgroup gens) (generatedSubgroup gens_inv)) => f1.
  set gens_rcons := rcons gens_inv (a_encoding p).
  have: in_generated_subgroup gens_inv (a_encoding p) => [|H];
    first by exists [:: Inverse 0] => /=; rewrite inv_involutive neutral_right.
  move: (generatedSubgroup_rcons_morphism gens_inv (a_encoding p) H:
    isomorphism (generatedSubgroup gens_inv) (generatedSubgroup gens_rcons)) => f2.
  set gens' := [:: a_encoding p; b_encoding (-q)].
  set gens_rcons' := rcons gens' (inv (a_encoding p)).
  set perm :(ordinal (size gens_rcons)) -> (ordinal (size gens_rcons')) :=
    fun x =>
      match x with
      | @Ordinal _ 0 _ => 2
      | @Ordinal _ 1 _ => 1
      | @Ordinal _ 2 _ => 0
      | _ => x
      end.
  have: injective perm => [|Hperm_inj];
    first by move => [] [|[|[|//]]] Hx [] [|[|[|//]]] Hy /= /eqP // _;
    rewrite (bool_irrelevance Hx Hy).
  have: bijective perm => [|Hperm];
    first by apply inj_card_bij => [//|] /=; apply leqnn.
  have: forall n, nth_gen gens_rcons n == nth_gen gens_rcons' (perm n) => [|Hequiv];
    first by move => [] [//|[|[//|//]]] /= _; rewrite -power_inv.
  move: (generatedSubgroup_perm_morphism gens_rcons gens_rcons' perm Hequiv Hperm:
    isomorphism (generatedSubgroup gens_rcons) (generatedSubgroup gens_rcons')) => f3.
  have: in_generated_subgroup gens' (inv (a_encoding p)) => [|H'];
    first by exists [:: Inverse 0] => /=; rewrite neutral_right.
  move: (generatedSubgroup_rcons_morphism' gens' (inv (a_encoding p)) H':
    isomorphism (generatedSubgroup gens_rcons') (generatedSubgroup gens')) => f4.
  by exact: (f4 \o f3 \o f2 \o f1).
Defined.

Definition pq_isomorphism_mod:
  isomorphism
    (generatedSubgroup gens)
    (generatedSubgroup [:: a_encoding (p %% q)%Z; b_encoding q]).
Proof.
  set gens' := [:: a_encoding (p %% q)%Z; b_encoding q].
  set gens_rcons := rcons gens (a_encoding (p %% q)%Z).
  have: in_generated_subgroup gens (a_encoding (p %% q)%Z) => [|H].
  - exists ((power (`[Base 1]_(FGP _)) (- (p %/ q)%Z)) @ [:: Base 0] @
           (power (`[Base 1]_(FGP _)) (p %/ q)%Z)).
    rewrite !morphism_preserve_law !morphism_preserve_power /=
            !neutral_right /b_encoding -!power_mul /a_encoding
            !associativity -power_add -!associativity
            -!power_inv -power_add.
    have: (q * - (p %/ q)%Z + p = p %%q)%Z => [|->]; first by lia.
    by have: (-p + q * (p %/ q)%Z = - (p %%q)%Z)%Z => [|->]; first by lia.
  - move: (generatedSubgroup_rcons_morphism gens (a_encoding (p %% q)%Z) H:
      isomorphism (generatedSubgroup gens) (generatedSubgroup gens_rcons)) => f1.
    set gens_rcons' := rcons gens' (a_encoding p).
    set perm :(ordinal (size gens_rcons)) -> (ordinal (size gens_rcons')) :=
      fun x =>
        match x with
        | @Ordinal _ 0 _ => 2
        | @Ordinal _ 1 _ => 1
        | @Ordinal _ 2 _ => 0
        | _ => x
        end.
    have: injective perm => [|Hperm_inj];
      first by move => [] [|[|[|//]]] Hx [] [|[|[|//]]] Hy /= /eqP // _;
      rewrite (bool_irrelevance Hx Hy).
    have: bijective perm => [|Hperm];
      first by apply inj_card_bij => [//|] /=; apply leqnn.
    have: forall n, nth_gen gens_rcons n == nth_gen gens_rcons' (perm n) => [|Hequiv];
      first by move => [] [//|[|[//|//]]] /= _.
    move: (generatedSubgroup_perm_morphism gens_rcons gens_rcons' perm Hequiv Hperm:
      isomorphism (generatedSubgroup gens_rcons) (generatedSubgroup gens_rcons')) => f2.
    have: in_generated_subgroup gens' (a_encoding p) => [|H'].
  -- exists ((power (`[Base 1]_(FGP _)) (p %/ q)%Z) @ [:: Base 0] @
        (power (`[Base 1]_(FGP _)) (- (p %/ q)%Z))).
     rewrite !morphism_preserve_law !morphism_preserve_power /=
              !neutral_right /b_encoding -!power_mul /a_encoding
              !associativity -power_add -!associativity
              -!power_inv -power_add.
     have: (q * (p %/ q)%Z + (p%%q)%Z = p)%Z => [|->]; first by lia.
     by have: (- (p %% q)%Z + q * - (p %/ q)%Z = - p)%Z => [|->]; first by lia.
  -- move: (generatedSubgroup_rcons_morphism' gens' (a_encoding p) H':
       isomorphism (generatedSubgroup gens_rcons') (generatedSubgroup gens')) => f3.
     by exact: (f3 \o f2 \o f1).
Defined.

Definition pq_isomorphism_mod':
  isomorphism
    (generatedSubgroup [:: a_encoding (p %% q)%Z; b_encoding q])
    (generatedSubgroup gens).
Proof.
  set gens' := [:: a_encoding (p %% q)%Z; b_encoding q].
  set gens_rcons' := rcons gens' (a_encoding p).
  have: in_generated_subgroup gens' (a_encoding p) => [|H'].
  - exists ((power (`[Base 1]_(FGP _)) (p %/ q)%Z) @ [:: Base 0] @
        (power (`[Base 1]_(FGP _)) (- (p %/ q)%Z))).
     rewrite !morphism_preserve_law !morphism_preserve_power /=
              !neutral_right /b_encoding -!power_mul /a_encoding
              !associativity -power_add -!associativity
              -!power_inv -power_add.
     have: (q * (p %/ q)%Z + (p%%q)%Z = p)%Z => [|->]; first by lia.
     by have: (- (p %% q)%Z + q * - (p %/ q)%Z = - p)%Z => [|->]; first by lia.
  - move: (generatedSubgroup_rcons_morphism gens' (a_encoding p) H':
       isomorphism (generatedSubgroup gens') (generatedSubgroup gens_rcons')) => f1.
    set gens_rcons := rcons gens (a_encoding (p %% q)%Z).

    set perm :(ordinal (size gens_rcons')) -> (ordinal (size gens_rcons)) :=
      fun x =>
        match x with
        | @Ordinal _ 0 _ => 2
        | @Ordinal _ 1 _ => 1
        | @Ordinal _ 2 _ => 0
        | _ => x
        end.
    have: injective perm => [|Hperm_inj];
      first by move => [] [|[|[|//]]] Hx [] [|[|[|//]]] Hy /= /eqP // _;
      rewrite (bool_irrelevance Hx Hy).
    have: bijective perm => [|Hperm];
      first by apply inj_card_bij => [//|] /=; apply leqnn.
    have: forall n, nth_gen gens_rcons' n == nth_gen gens_rcons (perm n) => [|Hequiv];
      first by move => [] [//|[|[//|//]]] /= _.
    move: (generatedSubgroup_perm_morphism gens_rcons' gens_rcons perm Hequiv Hperm:
      isomorphism (generatedSubgroup gens_rcons') (generatedSubgroup gens_rcons)) => f2.

    have: in_generated_subgroup gens (a_encoding (p %% q)%Z) => [|H].
  -- exists ((power (`[Base 1]_(FGP _)) (- (p %/ q)%Z)) @ [:: Base 0] @
           (power (`[Base 1]_(FGP _)) (p %/ q)%Z)).
     rewrite !morphism_preserve_law !morphism_preserve_power /=
             !neutral_right /b_encoding -!power_mul /a_encoding
             !associativity -power_add -!associativity
             -!power_inv -power_add.
     have: (q * - (p %/ q)%Z + p = p %%q)%Z => [|->]; first by lia.
     by have: (-p + q * (p %/ q)%Z = - (p %%q)%Z)%Z => [|->]; first by lia.
  -- move: (generatedSubgroup_rcons_morphism' gens (a_encoding (p %% q)%Z) H:
       isomorphism (generatedSubgroup gens_rcons) (generatedSubgroup gens)) => f3.
     by exact: (f3 \o f2 \o f1).
Defined.

End apbqIsomorphismHousekeeping.

Definition pq_isomorphism_nat (p q: int) (H: (q != 0)%Z):
  isomorphism
    (generatedSubgroup [:: a_encoding p; b_encoding q])
    (generatedSubgroup [:: a_encoding `|(p %% q)%Z|%N; b_encoding `|q|%N]).
Proof.
  move: (pq_isomorphism_mod p q H).
  have: ((p %% q)%Z = `|(p%% q)%Z|%N) => [|-> f1]; first by lia.
  case Hq0: (q >= 0)%Z.
  - have: (q = `|q|%N) => [|<-]; first by lia.
    by exact: f1.
  - move: (pq_isomorphism_inv (`|(p%%q)%Z|%N) q).
    have: ((-q)%Z = `|q|%N) => [|-> f2]; first by lia.
    by exact: (f2 \o f1).
Qed.

Definition pq_isomorphism_nat' (p q: int) (H: (q != 0)%Z):
  isomorphism
    (generatedSubgroup [:: a_encoding `|(p %% q)%Z|%N; b_encoding `|q|%N])
    (generatedSubgroup [:: a_encoding p; b_encoding q]).
Proof.
  move: (pq_isomorphism_mod' p q H).
  have: ((p %% q)%Z = `|(p%% q)%Z|%N) => [|-> f2]; first by lia.
  case Hq0: (q >= 0)%Z.
  - have: (q = `|q|%N) => [|<-]; first by lia.
    by exact: f2.
  - move: (pq_isomorphism_inv (`|(p %% q)%Z|%N) (-q)%Z).
    have: (- (-q)%Z = q) => [|->]; first by lia.
    have: ((-q)%Z = `|q|%N) => [|-> f1]; first by lia.
    by exact: (f2 \o f1).
Qed.

(* TODO(reiniscirpons): uncomment and fix once we have a lemma
   for the isomorphism. *)
Definition pqpq_isomorphism
  (p1 q1: int) (H1: (q1 != 0)%Z)
  (p2 q2: int) (H2: (q2 != 0)%Z):
    isomorphism
      (generatedSubgroup [:: a_encoding p1; b_encoding q1])
      (generatedSubgroup [:: a_encoding p2; b_encoding q2]).
Proof.
  move: (pq_isomorphism_nat p1 q1 H1) => f1.
  have: (`|(p1 %% q1)%Z|%N < `|q1|%N)%N => [|H1']; first by lia.
  move: (apbq_isomorphism_inv (`|(p1 %% q1)%Z|%N) (`|q1|%N) H1') => f2.
  have: (`|(p2 %% q2)%Z|%N < `|q2|%N)%N => [|H2']; first by lia.
  move: (apbq_isomorphism (`|(p2 %% q2)%Z|%N) (`|q2|%N) H2') => f3.
  move: (pq_isomorphism_nat' p2 q2 H2) => f4.
  exact: (f4 \o f3 \o f2 \o f1).
Defined.
