From elpi.apps Require Import coercion.
From HB Require Import structures.
From mathcomp Require Import ssreflect ssrfun ssrbool ssrint ssrnat.
From mathcomp Require Import eqtype seq fintype all_algebra.
From mathcomp Require Import ring lra zify.
Import GRing.Theory.
Require Import Setoid Morphisms.

From GWP Require Import Utils Equivalence EquivalenceAlgebra Presentation F2.

Open Scope int_scope.
Open Scope ring_scope.


(* Subgroup generated by a set of group elements *)
Section GeneratedSubgroup.

(* TODO(reiniscirpons): Change this to use image of free group. *)

Variable G: group.
Variable Sigma: finType.
Variable f: Sigma -> G.

Definition in_generated_subgroup (x: G): Prop :=
  exists (w: FreeGroup Sigma), \hat f w == x.

Lemma igs_law 
  (x y: G) (Hx: in_generated_subgroup x) (Hy: in_generated_subgroup y):
  in_generated_subgroup (x @ y).
Proof.
case: Hx => [wx Hx].
case: Hy => [wy Hy].
exists (wx @ wy) => /=.
rewrite morphism_preserve_law.
by rewrite Hx Hy.
Defined.

Lemma igs_e: in_generated_subgroup e.
Proof. by exists sa_e. Defined.

Lemma igs_inv (x: G) (Hx: in_generated_subgroup x): in_generated_subgroup (inv x).
Proof.
case: Hx => [astx Hx].
exists (sa_inv astx).
by rewrite Hx.
Defined.

HB.instance Definition _ := isSubgroupCharacterizer.Build G in_generated_subgroup igs_law igs_e igs_inv.

Lemma igs_gen (x: G) (Hx: genChar x): in_generated_subgroup x.
Proof.
unshelve eexists.
  exact: (sa_gen x).
done.
Defined.

Definition generatedSubgroup := subgroup_by in_generated_subgroup.

End GeneratedSubgroup.
Arguments generatedSubgroup {_}.
Arguments in_generated_subgroup {_}.
Arguments subgroup_ast {_}.
Arguments interpret_subgroup_ast {_ _}.
Arguments sa_e {_}.
Arguments sa_law {_ _}.
Arguments sa_inv {_ _}.
Arguments sa_gen {_ _}.
Arguments igs_gen {_ _}.

Definition finGeneratedSubgroup {G: group} (gens: seq G) := generatedSubgroup (fun x => in_list x gens).

(* Intersection of subgroups *)
Section SubgroupIntersection.
Variable G: group.
Variable (H1 H2: subgroup G).

Record is_in_intersection (x: G) : Prop := {
  intersection_in_left: x \insubgroup H1;
  intersection_in_right: x \insubgroup H2;
}.

Definition iii_P_law : forall (x y: G), is_in_intersection x -> is_in_intersection y -> is_in_intersection (x @ y).
Proof.
move=> x y [[x1 x1_eq] [x2 x2_eq]] [[y1 y1_eq] [y2 y2_eq]]; eexists.
- by exists (x1 @ y1); rewrite morphism_preserve_law -x1_eq -y1_eq.
- by exists (x2 @ y2); rewrite morphism_preserve_law -x2_eq -y2_eq.
Qed.

Definition iii_P_neutral : is_in_intersection e.
Proof. by eexists; exists e; rewrite morphism_preserve_e. Qed.

Definition iii_P_inv : forall (x: G), is_in_intersection x -> is_in_intersection (inv x).
Proof.
move=> x [[x1 x1_eq] [x2 x2_eq]]; eexists.
- by exists (inv x1); rewrite -morphism_preserve_inv -x1_eq.
- by exists (inv x2); rewrite -morphism_preserve_inv -x2_eq.
Qed.

HB.instance Definition _ := isSubgroupCharacterizer.Build G is_in_intersection iii_P_law iii_P_neutral iii_P_inv.

(* we could also prove that H1 /\ H2 is a subgroup of H1 and H2 *)

Definition intersection := subgroup_by is_in_intersection.

End SubgroupIntersection.
