From elpi.apps Require Import coercion.
From HB Require Import structures.
From mathcomp Require Import ssreflect ssrfun ssrbool ssrint ssrnat.
From mathcomp Require Import eqtype seq fintype all_algebra.
From mathcomp Require Import ring lra zify.
Import GRing.Theory.
Require Import Setoid Morphisms.

From GWP Require Import Utils Equivalence EquivalenceAlgebra Presentation F2.

Open Scope int_scope.
Open Scope ring_scope.

Import PresentationNotations.

(* Subgroup generated by a sequence of group elements *)
Section GeneratedSubgroup.

Variable G: group.
Variable gens: seq G.

Let Sigma: finType := ordinal (length gens).
Let nth_gen: Sigma -> G :=
  fun n => nth e gens n.

Definition in_generated_subgroup (x: G): Prop :=
  exists (w: FreeGroup Sigma), \hat nth_gen w == x.

Lemma igs_law 
  (x y: G) (Hx: in_generated_subgroup x) (Hy: in_generated_subgroup y):
  in_generated_subgroup (x @ y).
Proof.
case: Hx => [wx Hx].
case: Hy => [wy Hy].
exists (wx @ wy).
by rewrite morphism_preserve_law /= Hx Hy.
Defined.

Lemma igs_e: in_generated_subgroup e.
Proof. by exists e. Defined.

Lemma igs_inv (x: G) (Hx: in_generated_subgroup x):
  in_generated_subgroup (inv x).
Proof.
case: Hx => [astx Hx].
exists (inv astx).
by rewrite -morphism_preserve_inv /= Hx.
Defined.

HB.instance Definition _ := isSubgroupCharacterizer.Build 
  G in_generated_subgroup igs_law igs_e igs_inv.

(* TODO(reiniscirpons): Would be nicer to have 
   the lemma use (g: G) and then have
   g \in gens as a condition, but that doesn't typecheck.
*)
Lemma igs_gen (s: Sigma): in_generated_subgroup (nth_gen s).
Proof.
  exists `[Base s].
  unfold FreeGroup_universal_extension; unfold extension => /=.
  by rewrite neutral_right.
Defined.

Definition generatedSubgroup :=
  subgroup_by in_generated_subgroup.

Definition subgroup_projection:
  (FreeGroup Sigma) -> generatedSubgroup.
Proof.
  by move => w; exists (\hat nth_gen w); exists w.
Defined.

Lemma subgroup_projection_preserve_equiv:
  forall x y: FreeGroup Sigma,
    x == y -> subgroup_projection x == subgroup_projection y.
Proof.
  move => x y Heq; enough (H: \hat nth_gen x == \hat nth_gen y) => [//|].
  by apply morphism_preserve_equiv.
Qed.

HB.instance Definition _ := isSetoidMorphism.Build 
  _ _ subgroup_projection subgroup_projection_preserve_equiv.

Lemma subgroup_projection_preserve_e:
    subgroup_projection e == e.
Proof. by []. Qed.

Lemma subgroup_projection_preserve_law:
  forall x y,
    subgroup_projection (x @ y) == 
      subgroup_projection x @ subgroup_projection y.
Proof.
  move => x y;
  enough (H: \hat nth_gen (x @ y) == \hat nth_gen x @ \hat nth_gen y) => [//|].
  by rewrite morphism_preserve_law.
Qed.

HB.instance Definition _ := isMonoidMorphism.Build 
  _ _ subgroup_projection
  subgroup_projection_preserve_e
  subgroup_projection_preserve_law.

Lemma subgroup_projection_surjective:
  forall x: generatedSubgroup, exists w: FreeGroup Sigma,
    subgroup_projection w == x.
Proof.
  move => [x [w Hw]]; by exists w.
Qed.

HB.instance Definition _ := isSurjective.Build 
  _ _ subgroup_projection subgroup_projection_surjective.

End GeneratedSubgroup.
Arguments generatedSubgroup {_}.
Arguments in_generated_subgroup {_}.
Arguments igs_gen {_}.
Arguments subgroup_projection {_}.


(** In this section we develop the Nielsen-Schreier-Stalling
    theory of subgroups of the free group, as it applies
    to the subgroup generated by a_p = b^p a b^{-p} and b^q. *)
Section NielsenSchreierStalling.

Notation Sigma := (ordinal 2).
Notation F2P := (FGP Sigma).
Notation F2 := (FreeGroup Sigma).
Notation a := (`[Base 0]_F2P).
Notation b := (`[Base 1]_F2P).

(* NOTE(reiniscirpons): a_p = b^p a b^{-p} *)
Definition a_encoding (p: int): F2 := (power a p) @ b @ (power a (-p)).

(* NOTE(reiniscirpons): b^q is the other generator *)
Definition b_encoding (q: int): F2 := power b q.

(* NOTE(reiniscirpons): Housekeeping lemmas:

   <a_p, b^q> \isomorphic <a_p, b^{-q}> (they both equal to <a_p, b^q, b^-q>)
   <a_p, b^q> \isomorphic <a_-p, b^{-q}> (fix a and map b to b^{-1})
   => every <a_p, b^q> is isomorphic to some <a_p', b^q'> with 0 <= p, q.
   Furthermore, if p, q: nat and q != 0, then
   <a_p, b^q> \isomorphic <a_(modulo p q), b^q>
   (these subgroups are in fact equal since we get a_(p+kq) by
    conjugating by b^q)

   So, if q != 0 (which it has to be as otherwise we get a rank 1 subgroup,
   which is bad), then we can additionally assume that p < q.

   TODO(reiniscirpons): Implement these reductions
   TODO(reiniscirpons): Add a lemma to show that if we can mutually derive
       generating sets, then subgroups are isomorphic.
*)

Variable p q: nat.
Variable Hlt: lt p q.

Definition apbq_letter_projection (letter: Sigma) :=
match letter with
| (Ordinal 0 _) => a_encoding p
(* NOTE(reiniscirpons): we only have 2 cases, so this one codes for 1 *)
| _ => b_encoding p
end.

(* NOTE(reiniscirpons): This is the map a -> a_p and b -> b^q,
   we will show it is an isomorphism onto <a_p, b^q> later on. *)
Definition apbq_projection: morphism F2 F2 := \hat apbq_letter_projection.

Definition Stallings_automaton_transition
  (state: nat) (letter: sigma F2P): option (nat * F2) :=
match letter with
| Base (Ordinal 0 _) =>
    (* NOTE(reiniscirpons): State p corresponds to prefix b^p, if we read a
     * here, then we need to use the first gen, hence we output an a too.
     * It is a loop since b^p a b^{-p}^k = b^p a^k b^{-p}. *)
    if state == p then Some (state, `[Base 0]_F2P)
    (* NOTE(reiniscirpons): Impossible to read anywhere else, so fall off. *)
    else None
(* NOTE(reiniscirpons): a^{-1} is treated exactly the same, can only read it
 * after b^p, in which case we can read an arbitrary amount. *)
| Inverse (Ordinal 0 _) =>
    if state == p then Some (state, `[Inverse 0]_F2P)
    else None
(* NOTE(reiniscirpons): b's move the state around in a loop modulo q.
   b^{-1}'s do the same thing only in reverse. We count a b^q after
   a full loop and emit a b when its done. For b^-q, we count
   it immediately, as soon as the first b^{-1} is used. This is 
   a techical requirement because of how we calculate the coset representative
   later on. *)
| Base (Ordinal 1 _) =>
    if state == (q.-1) then Some (0, `[Base 1]_F2P)
    else Some (state.+1, `[]_F2P)
| Inverse (Ordinal 1 _) =>
    if state == 0 then Some (q.-1, `[Inverse 1]_F2P)
    else Some (state.-1, `[]_F2P)
| _ => None
end.

(* NOTE(reiniscirpons): This function attempts to find the largest left
   factor of a reduced word in F2 that is in the subgroup generated
   by <a_p, b^q>. It outputs a word `result` in F2 such that
   `result` maps to this factor via the apbq_projection function.
   Since the word is reduced, this notion is well defined
   (up to some convenstion about how to encode cosets).

   Essentially we just repeatedly apply the transition function above
   until we run out of letters, or we fall off the machine.*)
Fixpoint Stallings_automaton_quotient
  (state: nat) (word: F2): F2 :=
match word with
| nil => `[]_F2P
| letter::word' =>
    match (Stallings_automaton_transition state letter) with
    | None => `[]_F2P
    | Some (state', output) =>
        output @ (Stallings_automaton_quotient state' word')
    end
end.

(* NOTE(reiniscirpons): This function attempts to find the remainder after
   left division of a reduced word in F2 by <a_p, b^q>.
   It outputs a word in F2 that is a canonical right coset representative
   of the right coset of word with respect to the subgroup <a_p, b^q>. *)
Fixpoint Stallings_automaton_remainder
  (state: nat) (word: F2): F2 :=
match word with
| nil => power b state
| letter::word' => 
    match (Stallings_automaton_transition state letter) with
    | None => (power b state) @ word
    | Some (state', output) =>
      Stallings_automaton_remainder state' word'
    end
end.

Lemma Stallings_automaton_product: forall (state: nat) (w: F2),
  lt state q ->
  inv (power b state) @
  apbq_projection (Stallings_automaton_quotient state (FreeGroup_norm w)) @ 
  (Stallings_automaton_remainder state (FreeGroup_norm w)) == w.
Proof.
  move => state w; elim: w state => [|letter1 word IH] state Hstate.
  - by rewrite neutral_right /= inverse_right.
  case: word IH => [_|letter2 word].
  - rewrite FreeGroup_norm_1.

End NielsenSchreierStalling.
