From elpi.apps Require Import coercion.
From HB Require Import structures.
From mathcomp Require Import ssreflect ssrfun ssrbool ssrint ssrnat.
From mathcomp Require Import eqtype seq fintype all_algebra.
From mathcomp Require Import ring lra zify.
Import GRing.Theory.
Require Import Setoid Morphisms.

From GWP Require Import Utils Equivalence EquivalenceAlgebra Presentation F2.

Open Scope int_scope.
Open Scope ring_scope.

Import PresentationNotations.

(* Subgroup generated by a sequence of group elements *)
Section GeneratedSubgroup.

Variable G: group.
Variable gens: seq G.

(* TODO(reiniscirpons): Should I be using notations or local definitions?*)
Notation Sigma := (ordinal (length gens)).
Local Definition nth_gen := fun (n: Sigma) => nth e gens n.

Definition in_generated_subgroup (x: G): Prop :=
  exists (w: FreeGroup Sigma), \hat nth_gen w == x.

Lemma igs_law 
  (x y: G) (Hx: in_generated_subgroup x) (Hy: in_generated_subgroup y):
  in_generated_subgroup (x @ y).
Proof.
case: Hx => [wx Hx].
case: Hy => [wy Hy].
exists (wx @ wy).
by rewrite morphism_preserve_law /= Hx Hy.
Defined.

Lemma igs_e: in_generated_subgroup e.
Proof. by exists e. Defined.

Lemma igs_inv (x: G) (Hx: in_generated_subgroup x):
  in_generated_subgroup (inv x).
Proof.
case: Hx => [astx Hx].
exists (inv astx).
by rewrite -morphism_preserve_inv /= Hx.
Defined.

HB.instance Definition _ := isSubgroupCharacterizer.Build 
  G in_generated_subgroup igs_law igs_e igs_inv.

(* TODO(reiniscirpons): Would be nicer to have 
   the lemma use (g: G) and then have
   g \in gens as a condition, but that doesn't typecheck.
*)
Lemma igs_gen (s: Sigma): in_generated_subgroup (nth_gen s).
Proof.
  exists (`[Base s]_(FGP Sigma)).
  by rewrite /(\hat _) /extension /prod /= neutral_right.
Defined.

Definition generatedSubgroup :=
  subgroup_by in_generated_subgroup.

Definition subgroup_projection:
  (FreeGroup Sigma) -> generatedSubgroup.
Proof.
  by move => w; exists (\hat nth_gen w); exists w.
Defined.

Lemma subgroup_projection_preserve_equiv:
  forall x y: FreeGroup Sigma,
    x == y -> subgroup_projection x == subgroup_projection y.
Proof.
  move => x y Heq; enough (H: \hat nth_gen x == \hat nth_gen y) => [//|].
  by apply morphism_preserve_equiv.
Qed.

HB.instance Definition _ := isSetoidMorphism.Build 
  _ _ subgroup_projection subgroup_projection_preserve_equiv.

Lemma subgroup_projection_preserve_e:
    subgroup_projection e == e.
Proof. by []. Qed.

Lemma subgroup_projection_preserve_law:
  forall x y,
    subgroup_projection (x @ y) == 
      subgroup_projection x @ subgroup_projection y.
Proof.
  move => x y;
  enough (H: \hat nth_gen (x @ y) == \hat nth_gen x @ \hat nth_gen y) => [//|].
  by rewrite morphism_preserve_law.
Qed.

HB.instance Definition _ := isMonoidMorphism.Build 
  _ _ subgroup_projection
  subgroup_projection_preserve_e
  subgroup_projection_preserve_law.

Lemma subgroup_projection_surjective:
  forall x: generatedSubgroup, exists w: FreeGroup Sigma,
    subgroup_projection w == x.
Proof.
  move => [x [w Hw]]; by exists w.
Qed.

HB.instance Definition _ := isSurjective.Build 
  _ _ subgroup_projection subgroup_projection_surjective.

End GeneratedSubgroup.
Arguments generatedSubgroup {_}.
Arguments in_generated_subgroup {_}.
Arguments igs_gen {_}.
Arguments subgroup_projection {_}.


(** In this section we develop the Nielsen-Schreier-Stalling
    theory of subgroups of the free group, as it applies
    to the subgroup generated by a_p = b^p a b^{-p} and b^q. *)
Section NielsenSchreierStalling.

Notation Sigma := (ordinal 2).
Notation F2P := (FGP Sigma).
Notation F2 := (FreeGroup Sigma).
Notation o0 := (Ordinal (ltn_ord 0)).
Notation o1 := (Ordinal (ltn_ord 1)).
Notation a := (`[Base o0]_F2P).
Notation b := (`[Base o1]_F2P).

(* NOTE(reiniscirpons): a_p = b^p a b^{-p} *)
Definition a_encoding (p: int): F2 := (power b p) @ a @ inv (power b p).

(* NOTE(reiniscirpons): b^q is the other generator *)
Definition b_encoding (q: int): F2 := power b q.

Variable p q: nat.

Notation gens := [:: a_encoding p; b_encoding q].
(* TODO: Why is Gamma not equal to Sigma? Shouldn't they be because
         length gens computationally reduces to 2? *)
Notation Gamma := (ordinal (length gens)).
Notation IndexFG := (FreeGroup Gamma).
Notation H := (generatedSubgroup gens).

(* NOTE(reiniscirpons): This is the map a -> a_p and b -> b^q,
   we will show it is an isomorphism onto <a_p, b^q> later on. *)
(* TODO(reiniscirpons): Why does this not work without explicitly
        specifying the group and subgroup? *)
Definition apbq_projection: morphism IndexFG F2 := 
  (@subgroup_inj F2 H) \o (subgroup_projection gens).

(* NOTE(reiniscirpons): Housekeeping lemmas:

   <a_p, b^q> \isomorphic <a_p, b^{-q}> (they both equal to <a_p, b^q, b^-q>)
   <a_p, b^q> \isomorphic <a_-p, b^{-q}> (fix a and map b to b^{-1})
   => every <a_p, b^q> is isomorphic to some <a_p', b^q'> with 0 <= p, q.
   Furthermore, if p, q: nat and q != 0, then
   <a_p, b^q> \isomorphic <a_(modulo p q), b^q>
   (these subgroups are in fact equal since we get a_(p+kq) by
    conjugating by b^q)

   So, if q != 0 (which it has to be as otherwise we get a rank 1 subgroup,
   which is bad), then we can additionally assume that p < q.

   TODO(reiniscirpons): Implement these reductions
   TODO(reiniscirpons): Add a lemma to show that if we can mutually derive
       generating sets, then subgroups are isomorphic.
*)
Variable Hpq: (p < q)%N.

(* TODO(reiniscirpons): Is Local Lemma the correct thing here? *)
Local Lemma H0q: (0 < q)%N.
Proof. by case: q Hpq. Qed.

Local Lemma HPqq: (q.-1 < q)%N.
Proof. by case: q H0q. Qed.


Definition Stallings_automaton_transition
  (state: nat) (letter: sigma F2P): option (nat * IndexFG) :=
match letter with
| Base (Ordinal 0 _) =>
    (* NOTE(reiniscirpons): State p corresponds to prefix b^p, if we read a
     * here, then we need to use the first gen, hence we output an a too.
     * It is a loop since b^p a b^{-p}^k = b^p a^k b^{-p}. *)
    if state == p then Some (state, a)
    (* NOTE(reiniscirpons): Impossible to read anywhere else, so fall off. *)
    else None
(* NOTE(reiniscirpons): a^{-1} is treated exactly the same, can only read it
 * after b^p, in which case we can read an arbitrary amount. *)
| Inverse (Ordinal 0 _) =>
    if state == p then Some (state, inv a)
    else None
(* NOTE(reiniscirpons): b's move the state around in a loop modulo q.
   b^{-1}'s do the same thing only in reverse. We count a b^q after
   a full loop and emit a b when its done. For b^-q, we count
   it immediately, as soon as the first b^{-1} is used. This is 
   a techical requirement because of how we calculate the coset representative
   later on. *)
| Base (Ordinal 1 _) =>
    if state == (q.-1) then Some (0, b)
    else Some (state.+1, e)
| Inverse (Ordinal 1 _) =>
    if state == 0 then Some (q.-1, inv b)
    else Some (state.-1, e)
| _ => None
end.

(* NOTE(reiniscirpons): This function attempts to find the largest left
   factor of a reduced word in F2 that is in the subgroup generated
   by <a_p, b^q>. It outputs a word `result` in F2 such that
   `result` maps to this factor via the apbq_projection function.
   Since the word is reduced, this notion is well defined
   (up to some convenstion about how to encode cosets).

   Essentially we just repeatedly apply the transition function above
   until we run out of letters, or we fall off the machine.*)
Fixpoint Stallings_automaton_quotient
  (state: nat) (word: F2): IndexFG :=
match word with
| nil => e
| letter::word' =>
    match (Stallings_automaton_transition state letter) with
    | None => e
    | Some (state', output) =>
        output @ (Stallings_automaton_quotient state' word')
    end
end.

(* NOTE(reiniscirpons): This function attempts to find the remainder after
   left division of a reduced word in F2 by <a_p, b^q>.
   It outputs a word in F2 that is a canonical right coset representative
   of the right coset of word with respect to the subgroup <a_p, b^q>. *)
Fixpoint Stallings_automaton_remainder
  (state: nat) (word: F2): F2 :=
match word with
| nil => power b state
| letter::word' => 
    match (Stallings_automaton_transition state letter) with
    | None => (power b state) @ word
    | Some (state', output) =>
      Stallings_automaton_remainder state' word'
    end
end.

(* TODO(reiniscirpons): Is using locals here correct? *)
Local Definition Stallings_automaton_product_condition (w: F2): Prop :=
    forall (state: nat), 
      (state < q)%N ->
      apbq_projection (Stallings_automaton_quotient state w) @ 
      (Stallings_automaton_remainder state w)
      == (power b state) @ w.
 
Local Lemma Stallings_automaton_product_a: forall (w: F2),
  Stallings_automaton_product_condition w -> 
  Stallings_automaton_product_condition ((Base o0)::w).
Proof.
  rewrite /Stallings_automaton_product_condition; move => w H state Hsq;
  (* TODO(reiniscirpons): Any better way of doing this than locking? *)
  rewrite [apbq_projection]lock /= -lock.
  case Hsp: (state == p)%B.
  -  rewrite morphism_preserve_law {2}[apbq_projection]lock
      (* TODO(reiniscirpons): Why does it not do this unfolding automatically? *)
             /= /(\hat_) /extension /prod /= /nth_gen /=.
  (* TODO(reiniscirpons): Would be nice if there was some "monoid" or
     "group" tactic that essentially does all the busywork here and
     allows us to do rewrites modulo associativity. *)
    rewrite neutral_right -associativity -lock (H state Hsq).
    move/eqP: Hsp => ->; rewrite /a_encoding/=.
    (* NOTE(reiniscirpons): Like here all we are doing is just
       some busywork with multiplication and powers. I think
       this is some kind of algebraic structure, maybe a module,
       where we could just decide equality by jiggling things around.
       I guess I should implement it ... *)
    (* NOTE(reiniscirpons):
       group axioms -> dealt with by using free group normal forms, i.e.
       1. Use `rewrite !inverse_law` to move all inversions as low down
          in the term tree as possible, now all inverses should be at the
          bottom.
       2. Use `rewrite !inv_involutive` to remove repeated inversions.
       3. Use `rewrite !associativity` to linearize multiplication term
       4. Use `rewrite !neutral_left !neutral_right`
          to remove all identity elements (this is enough because we have a
          linear multiplication term of the form
            (..((x_0 * x_1) * x_2 ...) * x_n),
          if x_0 is not the identity, then there we cannot use neutral_left
          ever. So, the initial !neutral_left will cancel the longest 
          prefix of x_0 ... x_n that are all identities. Afterwards,
          we only need to use neutral_right as discussed.
       5. Set the innermost multiplication pair as the "active pair"
       6. Check if active multiplication pair cancels:
       6.1. if theactive pair is (x * inv(y)) or (inv(x) * y) and
            x and y are convertible terms (or whatever the proper terminology
            is, basically we want to treat each term as a generator of a
            free group, where the underlying equality is on terms),
            then replace the term by e
            (using either inverse_left or inverse_right) and then
            remove it using either neutral_left or neutral right.
            If we used neutral_right, then the new innermost term
            becomes active. If we used neutral left, then we need to
            use associativity to take the right element of the left subtree
            and move it up to be in a new active pair with the
            right element of the current node. The second situation
            situation is shown graphically below:
                   /
                  /|       /       /
                 / n      /|      /|
                /|       / n     / |
               / |   -> /|   -> / /|
              / /|     T r     T r n 
             /|a b
            T r
            Here (T r) is an already processed subtree whose right leaf is r,
            then a and b are elements of the
            active pair that cancel, leaving a neutral on the right, and n in the
            right sibling of the parent of the active pair. using a single call to
            associativity, we make r, n the new active pair.
       6.2. Otherwise, no cancellation happened, in this case we take the
            left term of multiplication and set it aside using two
            associativity calls:
                   /        /        /
                  /|       /|       /|
                 / n      / n      / |
                /|       /|       / /|
               / |   -> / b  ->  /|b n
              / /|     /|       T a
             T a b    T a
            here T is anready processed subtree, (a b) is the active pair
            and n is the right sibling of the parent of the active pair.
            The two calls to associativity make (b n) the new active pair
       7. If we got to the top of the tree, then the term is reduced with
          respect to the group axioms, i.e. no usage of the associativity,
          identity and inversion rewrites will yield a distinct term (up to
          associativity). Otherwise, got to 6.
    *)
    (* NOTE(reiniscirpons): exponential axioms:
        x^a * x^b = x^(a+b) -> should be fine
        (x*y)^a -> this is where we run into trouble...
       TODO(reiniscirpons): look up if the algebra of the free group with
        exponentiation has a normal form algorithm.
    *)
    by rewrite -!associativity (associativity (inv _)) inverse_right neutral_left.
  - rewrite /= /(\hat_) /extension /prod /=.
    by rewrite neutral_left.
Qed.

Local Lemma Stallings_automaton_product_invl_a: forall (w: F2),
  Stallings_automaton_product_condition w -> 
  Stallings_automaton_product_condition ((Inverse o0)::w).
Proof.
  rewrite /Stallings_automaton_product_condition; move => w H state Hsq;
  rewrite [apbq_projection]lock /= -lock.
  case Hsp: (state == p)%B.
  - rewrite morphism_preserve_law
    {2}[apbq_projection]lock /= /(\hat_) /extension /prod /=.
    rewrite neutral_right -associativity -lock (H state Hsq).
    move/eqP: Hsp => ->; rewrite /a_encoding/=.
    (* NOTE(reiniscirpons): by solve_group.*)
    by rewrite !inverse_law inv_involutive  -!associativity
               (associativity (inv (power _ _))) inverse_right neutral_left.
  - rewrite /= /(\hat_) /extension /prod /=.
    by rewrite neutral_left.
Qed.

Local Lemma Stallings_automaton_product_b: forall (w: F2),
  Stallings_automaton_product_condition w -> 
  Stallings_automaton_product_condition ((Base o1)::w).
Proof.
  rewrite /Stallings_automaton_product_condition; move => w H state Hsq;
  rewrite [apbq_projection]lock /= -lock.
  case HsqP: (state == q.-1)%B.
  - rewrite morphism_preserve_law
    {2}[apbq_projection]lock /= /(\hat_) /extension /prod /= /nth_gen /=.
    rewrite neutral_right -associativity -lock (H 0 H0q).
    move/eqP: HsqP => ->; rewrite /b_encoding/=.
    (* NOTE(reiniscirpons): by solve_group_powers *)
    rewrite power0 neutral_left (cons_law _ _ w) associativity.
    (* TODO(reiniscirpons): slighly annoying to do casework here,
           can we do better? *)
    by case: q H0q => [//|n _ /=]; rewrite powerS powerC'.
  (* TODO(reiniscirpons): Is there a faster way to conclude this? *)
  - have HSsq: (state.+1 < q)%N.
  -- rewrite leq_eqVlt in Hsq; case/orP: Hsq HsqP => [|//];
     by move/eqP => <-; rewrite eq_refl.
  -- rewrite morphism_preserve_law /= {1}/(\hat _) /extension /prod /=.
     rewrite neutral_left (H state.+1 HSsq).
     by rewrite (cons_law _ _ w) associativity powerS powerC'.
Qed.

Local Lemma Stallings_automaton_product_invl_b: forall (w: F2),
  Stallings_automaton_product_condition w -> 
  Stallings_automaton_product_condition ((Inverse o1)::w).
Proof.
  rewrite /Stallings_automaton_product_condition; move => w H state Hsq;
  rewrite [apbq_projection]lock /= -lock.
  case HsqP: (state == 0)%B.
  - rewrite morphism_preserve_law
    {2}[apbq_projection]lock /= /(\hat_) /extension /prod /= /nth_gen /=.
    rewrite neutral_right -associativity -lock (H q.-1 HPqq).
    case: q H0q => [//|m _ /=].
    move/eqP: HsqP => ->; rewrite /b_encoding/=.
    (* NOTE(reiniscirpons): by solve_group_powers *)
    by rewrite power0 neutral_left powerS -powerC' inverse_law -associativity
            (associativity (inv (power _ _))) inverse_right
            neutral_left.
  (* TODO(reiniscirpons): Is there a faster way to conclude this? *)
  - have HSsq: (state.-1 < q)%N.
  -- case: state Hsq HsqP => [//|state Hsq _ /=].
     by apply ltn_trans with state.+1.
  -- rewrite morphism_preserve_law /= {1}/(\hat _) /extension /prod /= /nth_gen /=.
     rewrite neutral_left (H state.-1 HSsq).
     case: state HsqP Hsq HSsq => [//|state _ _ _ /=].
     by rewrite (cons_law _ _ w) powerS -powerC' !associativity
             -(associativity _ b) inverse_left neutral_right.
Qed.


(* TODO(reiniscirpns):
   - try removing state < q assumption from induction,
     it is neccesary, but maybe if we made the state an element
     of a finType itself? But this leads yet to more complications... *)
Lemma Stallings_automaton_product: forall (w: F2),
  Stallings_automaton_product_condition w.
Proof.
  elim => [state _ /=|c w IH].
  (* TODO(reiniscirpons): Why are we not done by computation? *)
  - by rewrite /(\hat _) /extension /prod /= neutral_left neutral_right.
  - case: c => [|] [] [| [|//]] Hc.
  (* TODO(reiniscirpons): Why does Rocq not figure this out by itself? *)
  -- rewrite (bool_irrelevance Hc (ltn_ord 0)).
     by apply Stallings_automaton_product_a.
  -- rewrite (bool_irrelevance Hc (ltn_ord 1)).
     by apply Stallings_automaton_product_b.
  -- rewrite (bool_irrelevance Hc (ltn_ord 0)).
     by apply Stallings_automaton_product_invl_a.
  -- rewrite (bool_irrelevance Hc (ltn_ord 1)).
     by apply Stallings_automaton_product_invl_b.
Qed.

Lemma Stallings_automaton_remainder_correct:
  forall (x: F2), right_coset_eq H x (Stallings_automaton_remainder 0 x).
Proof.
  move => x; rewrite right_coset_eq'.
  exists (subgroup_projection gens (Stallings_automaton_quotient 0 x)).
  by apply Stallings_automaton_product; exact H0q.
Qed.

Lemma Stallings_automaton_remainder_subgroup:
  forall (state: nat) (w: F2),
  (* TODO(reiniscirpons): we have a bit of level switching here, since we are
   * now working with words versus group elements. In theory this is
   * distinguished by == versus =, but maybe there is a better way of
   * distinguishing it?*)
  Stallings_automaton_remainder
    state
    (power b (- (state: int)) @ apbq_projection w) = [::].
  (* TODO(reiniscirpons): Do this *)
Proof.
  elim => [|state IH w]; last first.
  (* NOTE(reiniscirpons): Wow, this just works! *)
  - by rewrite powerP -cons_law -cat_law /= IH.
  - elim => [//| [|] [] [| [|//]] Hc w];
    rewrite power0 -!cat_law [apbq_projection]lock /= -lock => IH.
  (* TODO(reiniscirpons): finish *)
Admitted.

Lemma Stallings_automaton_quotient_freely_reduced:
  forall (state: nat) (x w: F2),
  (state < q)%N ->
  freely_reduced x -> (power b state) @ x == apbq_projection w ->
  Stallings_automaton_quotient state x = FreeGroup_norm w.
  (* TODO(reiniscirpons): Do this *)
Admitted.


Lemma Stallings_automaton_remainder_unique:
  forall (statex statey: nat) (x y: F2),
  freely_reduced x ->
  freely_reduced y ->
  (right_coset_eq H ((power b statex) @ x) ((power b statey) @ y)  ->
  Stallings_automaton_remainder statex x =
  Stallings_automaton_remainder statey y).
  (* TODO(reiniscirpons): Do this *)
Admitted.


End NielsenSchreierStalling.
